### ISSUE TITLE
Unable to get calculated cells?

### ISSUE THREAD

**Issue by stuarthalloway** [cgrand/spreadmap#1]
When I access fixed-value cells, everything works as in the README, but for calculated cells I get 

```
NullPointerException   org.apache.poi.ss.formula.eval.forked.ForkedEvaluator.evaluate (ForkedEvaluator.java:115)
```

I made the spreadsheet by exporting from Numbers -- could that be doing something weird?

**Comment by cgrand** [comment]
Hi Stuart,

I only used it with simple (no ranges etc.) spreadsheets from LibreOffice or Excel, so Numbers may be the cause.
Can you provide me with a sample spreadsheet exported from Numbers and exhibiting the error? Did you export to xls or xlsx?

**Comment by cgrand** [comment]
I tried to export from Numbers to xls: the resulting file can't be open with LibreOffice and when imported into Google Sheet the formula is lost.

**Comment by stuarthalloway** [comment]
Now that #2 is fixed I can import from Google, and don't care about Numbers anymore. :-)
